github: [turgutoaydin, LiraKurdi]


community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username

custom: ['https://turgutoaydin.github.io/aagame/', 'https://turgutoaydin.github.io/aagame/']
